# Generated by Django 6.0.6 on 2026-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
