# Generated by Django 6.1.1 on 2026-10-02 23:30

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_personalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name_plural': 'PersonalInfo'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_techstack_name_ci', violation_error_message='This TeckStack already exists.')],
            },
        ),
    ]
