# Generated by Django 6.1.1 on 2026-10-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_personalinfo_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stacks',
            field=models.ManyToManyField(related_name='projects', to='projects.techstack'),
        ),
    ]
