# Generated by Django 6.1.1 on 2026-10-03 00:13

from django.db import migrations
from django.db import migrations


def copy_tech_stacks(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    TechStack = apps.get_model('projects', 'TechStack')

    for project in Project.objects.all():
        for raw_name in (project.tech_stack or '').split(','):
            name = raw_name.strip()
            if not name:
                continue
            stack = TechStack.objects.filter(name__iexact=name).first()
            if stack is None:
                stack = TechStack.objects.create(name=name)
            project.tech_stacks.add(stack)

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_tech_stacks'),
    ]

    operations = [
        migrations.RunPython(copy_tech_stacks, migrations.RunPython.noop),
    ]
