# Generated by Django 6.1.1 on 2026-10-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_copy_tech_stacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
