# Generated by Django 6.0.6 on 2026-07-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
