# Generated by Django 6.0.6 on 2026-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='author_role',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='created_at',
        ),
        migrations.AddField(
            model_name='testimony',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
